#! /bin/sh
#
# Copyright (c) 2012 Lawrence Teo <lteo@lteo.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Silly script to exit out of all multiplexed SSH connections

for i in $HOME/.ssh/ctl-*
do
	username=$(echo $i | cut -d- -f2)
	host=$(echo $i | cut -d- -f3)
	port=$(echo $i | cut -d- -f4)
	[ -z "$username" ] && continue
	[ -z "$host" ] && continue
	[ -z "$port" ] && continue
	echo Exiting $username@${host} port ${port}
	ssh -O exit -p $port $username@$host
done
